source $VIMRUNTIME/defaults.vim
let mapleader=" "
set bg=dark
set wildmenu 

set mouse=
set lazyredraw          " 延迟重绘（提升性能）
set backspace=indent,eol,start  " 更好的退格键行为
set whichwrap+=<,>,h,l  " 光标行首行尾时自动换行
set list
set listchars=tab:▸\ ,trail:␣,extends:>,precedes:<,nbsp:+

set shiftwidth=4        " 设置制表符宽度"
set expandtab           " 用空格代替制表符
set tabstop=4           " 设置制表符宽度"
set softtabstop=4
set virtualedit=block

set encoding=utf-8 " 设置 Vim 内部的编码
set fileencoding=utf-8 " 设置新文件的默认编码为 UTF-8
set fileencodings=utf-8,gbk,gb2312,gb18030,cp936,ucs-bom,big5,latin1 " 设置读取文件时尝试的编码顺序

set completeopt=menu,menuone,noselect,noinsert
set autoindent          " 继承前一行的缩进方式，特别适用于多行注释
set number              " 设置行号
set nrformats=
set hlsearch
set incsearch           " 在搜索时，输入的词句的逐字符高亮（类似firefox的搜索）

set cc=100
set ignorecase smartcase
set showmatch           " 显示匹配的括号
set autoread
set autowrite
set nowrap
set cursorline

set foldenable " 1. 启用折叠功能
set foldmethod=syntax
set foldlevelstart=99 " 3. 关键：文件打开时，所有折叠都展开
set foldnestmax=5 " 4. 限制最大嵌套层数，防止性能问题
"set foldcolumn=2 " 5. （可选）在左侧显示折叠标识列

set undofile
let s:cache = expand('~/.vimcache')
if !isdirectory(s:cache) | call mkdir(s:cache, 'p') | endif
let &undodir = s:cache
let g:netrw_home = s:cache

set nobackup            "允许生成备份文件"
set nowritebackup
set noswapfile          "允许生成swap文件"
set autochdir

set laststatus=2        " 显示状态栏
set statusline+=%#ErrorMsg#\ [%{toupper(mode())}]
set statusline+=\ %#DiffAdd#\ %F
set statusline+=\ %#MoreMsg#\%m%r%w
set statusline+=%#StatuslineNC#
set statusline+=%=
set statusline+=%#DiffAdd#
set statusline+=\ %Y\ \|
set statusline+=\ %{&fileencoding}\ \|
set statusline+=\ %{&fileformat}\ \|
set statusline+=\ %{(&bomb?\",BOM\":\"NOBOM\")}\ \|
set statusline+=\ %l/%L,%c\ (%p%%)

if executable('rg')
  set grepprg=rg\ --vimgrep\ --no-heading\ --smart-case
  set grepformat=%f:%l:%c:%m
endif

nnoremap <F6> :cnext<CR>
nnoremap <F7> :cprevious<CR>
nnoremap <F8> :cclose<CR>

nnoremap <leader>po :ptag <C-R><C-W><CR>
nnoremap <leader>pc :pclose<CR>
set previewpopup=height:15,width:80,border:round,highlight:Pmenu

colorscheme desert

if v:version <= 900
    finish
endif

if empty(glob($HOME."/.vim/autoload/plug.vim"))
    command! InsPlug :! curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    finish
endif

call plug#begin()
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
Plug 'ludovicchabant/vim-gutentags' "符号索引 
Plug 'skywind3000/gutentags_plus'

let $GTAGSLABEL = 'native-pygments' " 'native'
let $GTAGSCONF = expand('~/.gtags.conf')
"let g:gutentags_ctags_executable = expand('~/Projects/bins/bin/universal-ctags')
let g:gutentags_define_advanced_commands = 1
let g:gutentags_project_root = ['.root', '.svn', '.git', '.hg', '.project']
au BufRead,BufEnter * let g:gutentags_ctags_tagfile = &filetype.'.tags'
let g:gutentags_modules = []
if executable('ctags')
    let g:gutentags_modules += ['ctags']
endif
if executable('gtags-cscope') && executable('gtags')
    let g:gutentags_modules += ['gtags_cscope']
endif

let g:gutentags_ctags_exclude=['*.trace']

" 将自动生成的 ctags/gtags 文件全部放入 ~/.cache/tags 目录中，避免污染工程目录
let s:vim_tags = expand('~/.vimcache/tags')
let g:gutentags_cache_dir = s:vim_tags
if !isdirectory(s:vim_tags)                   "检测~/.cache/tags 不存在就新建
   silent! call mkdir(s:vim_tags, 'p')
endif

let g:gutentags_ctags_extra_args  = ['--fields=+niazSl']

if &filetype=='cpp'
    let g:gutentags_ctags_extra_args += ['--c++-kinds=+px']
endif
if &filetype=='c'
    let g:gutentags_ctags_extra_args += ['--c-kinds=+px']
endif

if &filetype=='fortran'
    let g:gutentags_ctags_extra_args += ['--fortran-kinds=+imv']
endif

" Get ctags version
let g:ctags_version = system('ctags --version')[0:8]

" 如果使用 universal ctags 需要增加下面一行
if g:ctags_version == "Universal"
    let g:gutentags_ctags_extra_args += ['--extras=+q', '--output-format=e-ctags']
    if &filetype=='markdown'
        let g:gutentags_ctags_extra_args += ['--markdown-kinds=+cs']
    endif
endif

let g:gutentags_auto_add_gtags_cscope = 1 " 禁用 gutentags 自动加载 gtags 数据库的行为
let g:gutentags_plus_switch = 1 "Change focus to quickfix window after search (optional).
"Enable advanced commands: GutentagsToggleTrace, etc.
let g:gutentags_define_advanced_commands = 1
let g:gutentags_trace = 0 "调试程序


""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
Plug 'dense-analysis/ale'
let g:ale_echo_msg_format = '[%linter%] %s [%severity%]'
let g:ale_set_loclist = 1
let g:ale_open_list = 0
let g:ale_keep_list_window_open = 0
let g:ale_lint_on_text_changed='always' "文件内容发生变化时不检查
let g:ale_lint_on_enter = 1  "打开文件时不检查

"使用clang对c和c++进行语法检查，对python使用pylint进行语法检查
let g:ale_linters = {
    \   'c++': ['clang','cppcheck','gcc'],
    \   'c': ['clang','cppcheck','gcc'],
    \   'python': ['pylint','flake8'],
    \}
        
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
Plug 'godlygeek/tabular'
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
Plug 'preservim/vim-markdown',{'for':['markdown']}
let g:vim_markdown_math = 1
let g:vim_markdown_folding_level = 6
let g:vim_markdown_frontmatter = 1
let g:tex_conceal = ""
let g:vim_markdown_conceal = 0
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
call plug#end()            " required
