source $VIMRUNTIME/defaults.vim
let mapleader=" "
set bg=dark
set wildmenu 

set mouse=
set lazyredraw          " 延迟重绘（提升性能）
set backspace=indent,eol,start  " 更好的退格键行为
set whichwrap+=<,>,h,l  " 光标行首行尾时自动换行
set list
set listchars=tab:▸\ ,trail:␣,extends:>,precedes:<,nbsp:+

set shiftwidth=4        " 设置制表符宽度"
set expandtab           " 用空格代替制表符
set tabstop=4           " 设置制表符宽度"
set softtabstop=4
set virtualedit=block

set encoding=utf-8 " 设置 Vim 内部的编码
set fileencoding=utf-8 " 设置新文件的默认编码为 UTF-8
set fileencodings=utf-8,gbk,gb2312,gb18030,cp936,ucs-bom,big5,latin1 " 设置读取文件时尝试的编码顺序

set completeopt=menu,menuone,noselect,noinsert
set autoindent          " 继承前一行的缩进方式，特别适用于多行注释
set number              " 设置行号
set nrformats=
set hlsearch
set incsearch           " 在搜索时，输入的词句的逐字符高亮（类似firefox的搜索）

set cc=100
set ignorecase smartcase
set showmatch           " 显示匹配的括号
set autoread
set autowrite
set nowrap
set cursorline

set foldenable " 1. 启用折叠功能
set foldmethod=syntax
set foldlevelstart=99 " 3. 关键：文件打开时，所有折叠都展开
set foldnestmax=5 " 4. 限制最大嵌套层数，防止性能问题
set foldcolumn=2 " 5. （可选）在左侧显示折叠标识列

set undofile
let s:cache = expand('~/.vimcache')
if !isdirectory(s:cache) | call mkdir(s:cache, 'p') | endif
let &undodir = s:cache
let g:netrw_home = s:cache

set nobackup            "允许生成备份文件"
set nowritebackup
set noswapfile          "允许生成swap文件"
set autochdir

set laststatus=2        " 显示状态栏
set statusline+=%#ErrorMsg#\ [%{toupper(mode())}]
set statusline+=\ %#DiffAdd#\ %F
set statusline+=\ %#MoreMsg#\%m%r%w
set statusline+=%#StatuslineNC#
set statusline+=%=
set statusline+=%#DiffAdd#
set statusline+=\ %Y\ \|
set statusline+=\ %{&fileencoding}\ \|
set statusline+=\ %{&fileformat}\ \|
set statusline+=\ %{(&bomb?\",BOM\":\"NOBOM\")}\ \|
set statusline+=\ %l/%L,%c\ (%p%%)

if executable('rg')
  set grepprg=rg\ --vimgrep\ --no-heading\ --smart-case
  set grepformat=%f:%l:%c:%m
endif

nnoremap <F6> :cnext<CR>
nnoremap <F7> :cprevious<CR>
nnoremap <F8> :cclose<CR>

colorscheme desert

if v:version <= 900
    finish
endif

if empty(glob($HOME."/.vim/autoload/plug.vim"))
    command! InsPlug :! curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    finish
endif

call plug#begin()
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" 安装 vim-lsp 和 asyncomplete 插件
Plug 'prabirshrestha/vim-lsp'
Plug 'mattn/vim-lsp-settings'  " 可选，自动配置 LSP 服务器
Plug 'prabirshrestha/asyncomplete.vim'
Plug 'prabirshrestha/asyncomplete-lsp.vim'

let g:asyncomplete_auto_popup = 1 
let g:asyncomplete_auto_completeopt = 0

let g:lsp_async_completion = 1           " [关键] 异步补全
let g:asyncomplete_min_chars = 2         " 延迟触发，降低负载
let g:lsp_completion_documentation_enabled = 0 " 如果需要文档就保持1，感觉慢可以设为0


" 当补全菜单可见时：
"   <Tab> 向下选择 (相当于 Ctrl-n)
"   <S-Tab> 向上选择 (相当于 Ctrl-p)
" 如果菜单不可见，则插入普通的 Tab 字符
inoremap <expr> <Tab>   pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<Tab>"

" 当补全菜单可见时：
"   用 <Enter> 确认选中项，并关闭菜单 (asyncomplete#close_popup())
"   而不是换行。如果菜单不可见，则正常换行。
inoremap <expr> <cr>    pumvisible() ? asyncomplete#close_popup() : "\<cr>"

let g:lsp_insert_text_enabled = 1
let g:lsp_text_edit_enabled = 1

" 基础 LSP 设置
let g:lsp_diagnostics_echo_cursor = 1
let g:lsp_diagnostics_float_cursor = 1
let g:lsp_diagnostics_highlights_delay = 200
let g:lsp_signs_enabled = 1
let g:lsp_signs_error = {'text': '✗'}
let g:lsp_signs_warning = {'text': '⚠'}
let g:lsp_signs_hint = {'text': '?'}
let g:lsp_signs_information = {'text': 'i'}

" C++ 配置 (使用 clangd)
if executable('clangd')
    au User lsp_setup call lsp#register_server({
        \ 'name': 'clangd',
        \ 'cmd': {server_info->['clangd']},
        \ 'allowlist': ['c', 'cpp', 'objc', 'objcpp'],
        \ })
endif

nmap <buffer> gi <plug>(lsp-call-hierarchy-incoming)
nmap <buffer> go <plug>(lsp-call-hierarchy-outgoing)


""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
Plug 'godlygeek/tabular'
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
Plug 'preservim/vim-markdown',{'for':['markdown']}
let g:vim_markdown_math = 1
let g:vim_markdown_folding_level = 6
let g:vim_markdown_frontmatter = 1
let g:tex_conceal = ""
let g:vim_markdown_conceal = 0
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
call plug#end()            " required
