source $VIMRUNTIME/defaults.vim
let mapleader=" "
set bg=dark
set wildmenu 

set mouse=
set lazyredraw          " 延迟重绘（提升性能）
set backspace=indent,eol,start  " 更好的退格键行为
set whichwrap+=<,>,h,l  " 光标行首行尾时自动换行
set list
set listchars=tab:▸\ ,trail:␣,extends:>,precedes:<,nbsp:+

set shiftwidth=4        " 设置制表符宽度"
set expandtab           " 用空格代替制表符
set tabstop=4           " 设置制表符宽度"
set softtabstop=4
set virtualedit=block

set encoding=utf-8 " 设置 Vim 内部的编码
set fileencoding=utf-8 " 设置新文件的默认编码为 UTF-8
set fileencodings=utf-8,gbk,gb2312,gb18030,cp936,ucs-bom,big5,latin1 " 设置读取文件时尝试的编码顺序

set completeopt=menu,menuone,noselect,noinsert
set autoindent          " 继承前一行的缩进方式，特别适用于多行注释
set number              " 设置行号
set nrformats=
set hlsearch
set incsearch           " 在搜索时，输入的词句的逐字符高亮（类似firefox的搜索）

set cc=100
set ignorecase smartcase
set showmatch           " 显示匹配的括号
set autoread
set autowrite
set nowrap
set cursorline

set foldenable " 1. 启用折叠功能
set foldmethod=syntax
set foldlevelstart=99 " 3. 关键：文件打开时，所有折叠都展开
set foldnestmax=5 " 4. 限制最大嵌套层数，防止性能问题
set foldcolumn=2 " 5. （可选）在左侧显示折叠标识列

set undofile
let s:cache = expand('~/.vimcache')
if !isdirectory(s:cache) | call mkdir(s:cache, 'p') | endif
let &undodir = s:cache
let g:netrw_home = s:cache

set nobackup            "允许生成备份文件"
set nowritebackup
set noswapfile          "允许生成swap文件"

set laststatus=2        " 显示状态栏
set statusline+=%#ErrorMsg#\ [%{toupper(mode())}]\
set statusline+=%#DiffAdd#\ %F
set statusline+=\ %#MoreMsg#\%m%r%w
set statusline+=%#StatuslineNC#
set statusline+=%=
set statusline+=%#DiffAdd#
set statusline+=\ %Y\ \|
set statusline+=\ %{&fileencoding}\ \|
set statusline+=\ %{&fileformat}\ \|
set statusline+=\ %{(&bomb?\",BOM\":\"NOBOM\")}\ \|
set statusline+=\ %l/%L,%c\ (%p%%)

if executable('rg')
  set grepprg=rg\ --vimgrep\ --no-heading\ --smart-case
  set grepformat=%f:%l:%c:%m
endif

nnoremap <F6> :cnext<CR>
nnoremap <F7> :cprevious<CR>
nnoremap <F8> :cclose<CR>

colorscheme desert
if v:version < 900
    finish
endif

if empty(glob($HOME."/.vim/autoload/plug.vim"))
    command! InsPlug :! curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    finish
endif

call plug#begin()
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
Plug 'neoclide/coc.nvim', {'branch': 'release'}
let g:coc_config_home = s:cache
let g:coc_data_home   = s:cache
let g:coc_global_extensions = [
            \ 'coc-clangd',  'coc-pyright',
            \ 'coc-snippets','coc-highlight', 'coc-git',
            \ 'coc-pairs','coc-lists'
            \ ]

nmap <silent> gd <Plug>(coc-definition)
nmap <silent> gy <Plug>(coc-type-definition)
nmap <silent> gi <Plug>(coc-implementation)
nmap <silent> gr <Plug>(coc-references)

" 用 <space>e 开关文件树
nmap <leader>e :CocCommand explorer<CR>
" 代码编辑
nmap <leader>f <Plug>(coc-format)
nmap <leader>ff <Plug>(coc-format-selected)
nmap <leader>rn <Plug>(coc-rename)    " 重命名符号

" Tab 在补全菜单/ snippet 占位符间跳转
inoremap <silent><expr> <TAB>
      \ coc#pum#visible() ? coc#pum#next(1) :
      \ coc#expandableOrJumpable() ? "\<C-r>=coc#rpc#request('doKeymap', ['snippets-expand-jump',''])\<CR>" :
      \ "\<Tab>"

" 诊断和错误处理
nmap <silent> [g <Plug>(coc-diagnostic-prev) " 上一个错误
nmap <silent> ]g <Plug>(coc-diagnostic-next) " 下一个错误

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
Plug 'godlygeek/tabular'
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
Plug 'preservim/vim-markdown',{'for':['markdown']}
let g:vim_markdown_math = 1
let g:vim_markdown_folding_level = 6
let g:vim_markdown_frontmatter = 1
let g:tex_conceal = ""
let g:vim_markdown_conceal = 0
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
call plug#end()            " required
